use NPX only on Windows

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -43,8 +43,18 @@ jobs:
 
       - run: node --throw-deprecation --trace-warnings --expose-gc node_modules/jest/bin/jest --forceExit --colors --logHeapUsage --runInBand --ci --detectOpenHandles --detectLeaks --coverage
 
-      - name: Upload coverage to Codecov
+      - name: Upload coverage to Codecov (NPX)
+        if: matrix.os == 'windows-latest'
         # https://github.com/codecov/codecov-bash/blob/1044b7a243e0ea0c05ed43c2acd8b7bb7cef340c/codecov#L158
-        run: npx codecov -f "./coverage/coverage-final.json"
+        run: npx codecov -f "./coverage/coverage-final.json" --disable=gcov
+        env:
+          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
+
+      - name: Upload client coverage to Codecov (Bash)
+        if: matrix.os != 'windows-latest'
+        # https://github.com/codecov/codecov-bash/blob/1044b7a243e0ea0c05ed43c2acd8b7bb7cef340c/codecov#L158
+        run: bash <(curl -s https://codecov.io/bash)
+          -f ./coverage/coverage-final.json
+          -Z || echo 'Codecov upload failed'
         env:
           CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
